# Generated by Django 2.0.5 on 2018-07-13 13:47

from django.db import migrations, models
import enumchoicefield.fields
import roses.models


class Migration(migrations.Migration):

    dependencies = [
        ('roses', '0002_auto_20180510_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='feed',
            name='show_as',
            field=enumchoicefield.fields.EnumChoiceField(default=roses.models.FeedDisplayStyle(1), enum_class=roses.models.FeedDisplayStyle, max_length=11, verbose_name='Display article as'),
        ),
    ]
